CREATE DATABASE banco_instituto;
USE banco_instituto;

/*FUNÇÃO PARA MOSTRAR TODAS AS TABELAS*/
SHOW TABLES;

/*CRIAÇÃO DA TABELA USUÁRIO*/
CREATE TABLE usuario (
    id_usuario INT PRIMARY KEY AUTO_INCREMENT,
    nome_usuario VARCHAR(255) NOT NULL,
    sobrenome_usuario VARCHAR(255) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(255) NOT NULL
);
/*MOSTRA DADOS DA TABELA USUÁRIO*/
SELECT * FROM usuario;
/*MOSTRAR A ESTRUTURA DA TABELA USUÁRIO*/
DESCRIBE usuario;


/*CRIAÇÃO DA TABELA ADMINSTRADOR*/
CREATE TABLE adm (
	id_adm INT PRIMARY KEY AUTO_INCREMENT,
    nome_adm VARCHAR(255) NOT NULL,
    sobrenome_adm VARCHAR(255) NOT NULL,
    cpf_adm VARCHAR(14) UNIQUE NOT NULL,
    atuacao_adm VARCHAR(50) NOT NULL,
    cargo_adm VARCHAR(100) NOT NULL,
    nome_empresa VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) UNIQUE NOT NULL,
    cep_empresa VARCHAR(8) UNIQUE NOT NULL
);
/*MOSTRA DADOS DA TABELA ADMINISTRADOR*/
SELECT * FROM adm;
/*MOSTRAR A ESTRUTURA DA TABELA ADMINISTRADOR*/
DESCRIBE adm;


/*CRIAÇÃO DA TABELA EVENTOS*/
CREATE TABLE eventos (
    id_evento INT PRIMARY KEY AUTO_INCREMENT,
    id_adm INT UNIQUE,
    nome_evento VARCHAR(255) NOT NULL,
    preco VARCHAR(100) NOT NULL,
    data_hora DATETIME NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    descricao TEXT,
    organizadores VARCHAR(255),
    FOREIGN KEY (id_adm) REFERENCES adm(id_adm) ON DELETE SET NULL
);
/*MOSTRA DADOS DA TABELA EVENTOS*/
SELECT * FROM eventos;
/*MOSTRAR A ESTRUTURA DA TABELA EVENTOS*/
DESCRIBE eventos;


/*CRIAÇÃO DA TABELA IMAGENS*/
CREATE TABLE imagens (
    id_imagem INT PRIMARY KEY AUTO_INCREMENT,
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho_imagem VARCHAR(255) NOT NULL,
    upload_imagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_imagem VARCHAR(50)
);
/*MOSTRA DADOS DA TABELA IMAGENS*/
SELECT * FROM imagens;
/*MOSTRAR A ESTRUTURA DA TABELA IMAGENS*/
DESCRIBE imagens;